# create a new namespace for this project
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    k8s-app: elasticsearch

# exposing service using type nodeport so that pods can be accessed from outside the EKS cluster
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: logging
  labels:
    k8s-app: elasticsearch
    kubernetes.io/name: "Elasticsearch"
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
    nodePort: 31312 # [if not defined pics random port from nodeport list of ports]
  selector:
    k8s-app: elasticsearch
apiVersion: v1


