## Role Based Acces Control ##
# creating Service account for authentication and authorization
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-service-account
  namespace: logging
  labels:
    k8s-app: elasticsearch

# cluster role mentioning which rules, resources and verbs shall be allowed when service account "elasticsearch-service-account" is in use.
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-cluster-role
  labels:
    k8s-app: elasticsearch
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"

# bindind service account "elasticsearch-service-account" with cluster role "elasticsearch-cluster-role"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: logging
  name: elasticsearch-cluster-role-binding
  labels:
    k8s-app: elasticsearch
subjects:
- kind: ServiceAccount
  name: elasticsearch-service-account
  namespace: logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elasticsearch-cluster-role
  apiGroup: ""