# Creating an Elasticsearch v6.8.18 cluster using stateful sets.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-stateful-set
  namespace: logging
  labels:
    k8s-app: elasticsearch
    version: v6.8.18
spec:
  # to ensure that the ES luster is highly available will deploy 2 ES pods
  replicas: 2 
  serviceName: elasticsearch-service
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: elasticsearch
      version: v6.8.18
  # to ensure that every new pod that comes up will be added a pvc of 2Gb (AWS EBS volume)
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        version: v6.8.18
        kubernetes.io/cluster-service: "true"
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: elasticsearch-service-account
      # affinities set will ensure that there is no more that one elasticsearch pod on each worker node.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - elasticsearch
            topologyKey: kubernetes.io/hostname
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.8.18
        name: elasticsearch-container      
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE           
        # as  CPU is required during initialization, therefore associating it dedicated cpu
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        # port for accepting data
        - containerPort: 9200
          name: db
          protocol: TCP
        # port for sending data
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-volume
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-init-container
        securityContext:
          privileged: true
